Enchance/eslint rules
wizeline/wize-q-remix pull request #130
Opened 2022-12-09 01:39 UTC by GeorginaFraire

#### What does this PR do?
(A brief explanation synthesizing the feature, bug or fix.)
- this
- that

#### Where should the reviewer start?
(Explain where the reviewer should start in order to review the whole addition or subtractions.)
:checkered_flag:

#### How should this be manually tested?
(List of steps to reproduce, corroborate or tests to run. Write this section clear enough so that external users can also follow it and test the fix.)
1. :one:
2. :two:
3. :tada:

#### Any background context you want to provide?
(Any information regarding the PR that the reviewer should know.)
:construction:

#### What are the relevant tickets?
(Link to issues, related PR, JIRA issues, etc.)
Closes #x

#### Screenshots
(Screenshots of the feature if available.)
:camera:

#### Questions
(If available, to another developer or reviewer.)
:question:

2022-12-09 16:09 UTC, Carlos-Reyna approved these changes

2022-12-09 18:37 UTC, Hoosep requested changes
This is changing absolute import to relative imports. I don't know if this is because of new rules of eslint but I guess does.

https://medium.com/geekculture/making-life-easier-with-absolute-imports-react-in-javascript-and-typescript-bbdab8a8a3a1

2022-12-09 18:39 UTC, Hoosep requested changes

2022-12-09 18:39 UTC, Hoosep commented on app/components/AdminUsersTable/AdminUsersTable.jsx
> +import { usePagination, DOTS } from '../../utils/hooks/usePagination';
This file is an example.

2022-12-13 13:40 UTC, GeorginaFraire commented on app/components/AdminUsersTable/AdminUsersTable.jsx
> +import { usePagination, DOTS } from '../../utils/hooks/usePagination';
Done

2022-12-13 15:30 UTC, Hoosep approved these changes

2022-12-13 21:46 UTC, merged