feat: update Question Card style
wizeline/wize-q-remix pull request #69
Opened 2022-11-03 19:44 UTC by AlonsoMtzG

#### What does this PR do?
- Updates question card styles

#### Where should the reviewer start?
- app/components/QuestionCard

#### How should this be manually tested?
1. Make sure that the component behaves normally and looks correctly in desktop and mobile version
2. 🎉

#### Any background context you want to provide?
It affects how QuestionDetail page looks, but It will be fixed in #68 

#### What are the relevant tickets?
Closes #58 

#### Screenshots
<img width="1440" alt="Captura de Pantalla 2022-11-03 a la(s) 13 12 21" src="https://user-images.githubusercontent.com/71342528/199815433-6fbc71c8-fd3a-4cbd-96de-241588b78d7f.png">
<img width="324" alt="Captura de Pantalla 2022-11-03 a la(s) 13 11 25" src="https://user-images.githubusercontent.com/71342528/199815496-97fa0495-4a84-41be-be06-117791e480da.png">

#### Questions
Now if a department is not assigned to a question, the Department label is not displayed,  is that ok or should the 'Not Assigned' label be displayed?

2022-11-03 22:20 UTC, Hoosep requested changes

2022-11-03 22:20 UTC, Hoosep commented on app/components/AnswerRow/AnswerRow.Styled.jsx
> +  padding: 15px 20px 10px 20px;
I suggest to use shorthand with three values 15px 20px 10px;

2022-11-03 22:20 UTC, Hoosep commented on app/components/AnswerRow/AnswerRow.Styled.jsx
> +    padding: 15px 12px 10px 12px;
Same. Shorthand could be useful:)

2022-11-04 16:16 UTC, albertcastaned approved these changes
LGTM 💯 About your question, I think i agree with not showing "Not Assigned" as you changed it. Great majority of questions are unassigned and it could get very repetitive how it was before.

2022-11-07 16:34 UTC, merged